#!/usr/bin/env python
__coding__ = "utf-8"
__author__ = "张宇航"

"""
-------------------------------------------------
   Description :	TODO：
   SourceFile  :	canny
   Author      :	zhangyuhang
   Date	       :	2024-10-18
-------------------------------------------------
"""
import numpy as np
import cv2

img = cv2.imread('lenna.png',0)
cv2.imshow('canny',cv2.Canny(img,100,150))
cv2.waitKey(0)
cv2.destroyAllWindows()
