#!/usr/bin/env python
__coding__ = "utf-8"
__author__ = "张宇航"

"""
-------------------------------------------------
   Description :	TODO：实现临近插值
   SourceFile  :	NearestInter
   Author      :	zhangyuhang
   Date	       :	2024-09-12
-------------------------------------------------
"""
import cv2
import numpy as np

def function(img):
    print('实现方法')
    h, w , channels = img.shape
    emptyImage = np.zeros((800, 800, channels), np.uint8)
    sh = h/800
    wh = w/800
    for k in range(channels):
        for i in range(800):
            for j in range(800):
                x = int(i*sh+0.5) #这里加0.5是为了防止四舍五入差距太大
                y = int(j*wh+0.5)
                emptyImage[i,j] = img[x,y]
    return emptyImage

img = cv2.imread('lenna.png')
zoom1 = cv2.resize(img,(800,800),interpolation=cv2.INTER_NEAREST)
zoom = function(img)
# print(zoom1)
# print(zoom1.shape)
cv2.imshow("nearest interp",zoom)
cv2.imshow("nearest interp1",zoom1)
# cv2.imshow("image",img)
cv2.waitKey(0)

