#!/usr/bin/env python
#-*- coding:utf-8 -*-
#author JiaJia time:2024-10-14
import cv2
import numpy as np
img = cv2.imread("2024.jpg",1)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow("canny",cv2.Canny(gray,10,100))
cv2.waitKey()
cv2.destroyALLWindows()

