#!/usr/bin/env python
__coding__ = "utf-8"
__author__ = "张宇航"

"""
-------------------------------------------------
   Description :	TODO：
   SourceFile  :	Noise噪声调用
   Author      :	zhangyuhang
   Date	       :	2024-10-17
-------------------------------------------------
"""
import cv2 as cv
import numpy as np
from PIL import Image
from skimage import util

img = cv.imread('lenna.png')
noise_ps_img = util.random_noise(img,mode='poisson')

cv.imshow('source', img)
cv.imshow('lenna', noise_ps_img)

cv.waitKey(0)
cv.destroyAllWindows()
