#!/usr/bin/env python
__coding__ = "utf-8"
__author__ = "张宇航"

"""
-------------------------------------------------
   Description :	TODO：
   SourceFile  :	PCA
   Author      :	zhangyuhang
   Date	       :	2024-10-18
-------------------------------------------------
"""
import matplotlib.pyplot as plt
import sklearn.decomposition as dp
from sklearn.datasets._base import load_iris

x,y = load_iris(return_X_y=True)
pca = dp.PCA(n_components=2)
reduced_x = pca.fit_transform(x)

red_x,red_y = [],[]
blue_x,blue_y = [],[]
green_x,grenn_y = [],[]
for i in range(len(reduced_x)):
    if y[i]==0:
        red_x.append(reduced_x[i][0])
        red_y.append(reduced_x[i][1])
    elif y[i] == 1:
        blue_x.append(reduced_x[i][0])
        blue_y.append(reduced_x[i][1])
    else:
        green_x.append(reduced_x[i][0])
        grenn_y.append(reduced_x[i][1])

plt.scatter(red_x,red_y,c='r',marker='x')
plt.scatter(blue_x,blue_y,c='b',marker='D')
plt.scatter(green_x,grenn_y,c='g',marker='.')
plt.show()
