#!/usr/bin/env python
__coding__ = "utf-8"
__author__ = "张宇航"

"""
-------------------------------------------------
   Description :	TODO：
   SourceFile  :	GaussianNoise高斯噪声
   Author      :	zhangyuhang
   Date	       :	2024-10-17
-------------------------------------------------
"""
import numpy as np
import cv2
from numpy import shape
import random


def GaussianNoise(src, means, sigma, percetage):
    NoiseImg = src
    NoiseNum = int(percetage * src.shape[0] * src.shape[1])
    for i in range(NoiseNum):
        randX = random.randint(0, src.shape[0] - 1)
        randY = random.randint(0, src.shape[1] - 1)

        NoiseImg[randX, randY] = NoiseImg[randX, randY] + random.gauss(means, sigma)

        if NoiseImg[randX, randY] < 0:
            NoiseImg[randX, randY] = 0
        elif NoiseImg[randX, randY] > 255:
            NoiseImg[randX, randY] = 255
    return NoiseImg


# 直接读取时设置为读取为灰度图像
img = cv2.imread('lenna.png', 0)
img1 = GaussianNoise(img, 1, 2, 0.8)
# 读取后再转换为灰度图像
img = cv2.imread('lenna.png')
img2 = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow('source', img2)
cv2.imshow('lenna_GussianNoise', img1)
cv2.waitKey(0)
